#!/usr/bin/env bash

if [[ -e task.bash ]]; then
  source ./task.bash
else
  taskBash=$(curl -s https://raw.githubusercontent.com/binaryphile/ansible/main/task.bash) || exit
  eval "$taskBash"
  unset -v taskBash
esac

main() {
  section system
  section dotfiles
  section nix
}

system() {
  task 'apt update and upgrade'
  def() {
    sudo apt update -qq && sudo apt upgrade -y
  }
  run

  task 'turn off motd'
  ok '[[ $(<$HOME/.local/share/cros-motd) == 5 ]]'
  def() {
    echo 5 >$HOME/.local/share/cros-motd
  }
  run

  task 'create required directories' mkdir -pm 755 $HOME/'$1' <<'  END'
    .config/liquidprompt
    .config/nixpkgs
    .config/ranger
    .local/share/nvim/site/autoload
  END

  task 'set up ssh directory'
  ok '[[ -d $HOME/.ssh ]]'
  def mkdir -m 700 $HOME/.ssh
}

dotfiles() {
  task 'clone dotfiles repository'
  ok '[[ -e $HOME/dotfiles ]]'
  def git clone https://github.com/binaryphile/dotfiles.git $HOME/dotfiles

  task 'link context file'
  ok '[[ -e $HOME/dotfiles/context ]]'
  def ln -s contexts/work/crostini-bullseye $HOME/dotfiles/context

  task 'create dotfile symlinks'
  def() {
    local -A link="( $1 )" # expand value to associative array
    ln -sf $HOME/dotfiles/${link[src]} $HOME/${link[path]}
  }
  loop <<'  END'
    [src]=bash/init.bash               [path]=.profile
    [src]=bash/init.bash               [path]=.bash_profile
    [src]=bash/init.bash               [path]=.bashrc
    [src]=gitconfig                    [path]=.gitconfig
    [src]=liquidprompt/liquid.theme    [path]=.config/liquidprompt/liquid.theme
    [src]=liquidprompt/liquidpromptrc  [path]=.config/liquidpromptrc
    [src]=ssh/config                   [path]=.ssh/config
    [src]=tmux.conf                    [path]=.tmux.conf
    [src]=ranger/rc.conf               [path]=.config/ranger/rc.conf
  END
}

nix() {
  task 'install nix'
  ok '[[ -e /nix/var/nix/profiles/default/bin/nix-env ]]'
  def() {
    curl -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm
  }
  run
  PATH+=:/nix/var/nix/profiles/default/bin

  task 'add home manager channel'
  ok '[[ -e $HOME/.nix-channels ]]'
  def nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager

  task 'update nix channels'
  ok '[[ -e $HOME/.nix-defexpr/channels/home-manager ]]'
  def nix-channel --update

  task 'install home manager'
  ok '[[ -e $HOME/.config/home-manager ]]'
  def nix-shell '<home-manager>' -A install

  task 'create nix configuration symlinks'
  def() {
    local -A link="( $1 )" # expand value to associative array
    ln -sf $HOME/dotfiles/${link[src]} $HOME/.config/${link[path]}
  }
  loop <<'  END'
    [src]=home.nix    [path]=home-manager/home.nix
    [src]=config.nix  [path]=nixpkgs/config.nix
  END

  task 'apply home manager configuration'
  def() {
    source $HOME/.nix-profile/etc/profile.d/hm-session-vars.sh
    home-manager switch
  }
  run
}

return 2>/dev/null
set -eu

[[ ${1:-} == --trace ]] && { shift; set -x; }

main
summarize
