- hosts: localhost
  environment:
    PATH: "{{ ansible_env.PATH }}:/nix/var/nix/profiles/default/bin"

  tasks:
    - name: Create required directories
      file:
        path: "$HOME/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - .config/liquidprompt
        - .config/ranger
        - tmp
        - .local/share/nvim/site/autoload

    - name: Set up SSH directory
      file:
        path: "$HOME/.ssh"
        state: directory
        mode: '0700'

    - name: Clone dotfiles repository
      git:
        repo: https://github.com/binaryphile/dotfiles.git
        dest: "$HOME/dotfiles"

    - name: Link context file
      file:
        src: "contexts/work/crostini-bullseye"
        path: "$HOME/dotfiles/context"
        state: link

    - name: Create dotfile symlinks
      file:
        src: "$HOME/dotfiles/{{ item.src }}"
        path: "$HOME/{{ item.path }}"
        state: link
        force: yes
      loop:
        - { src: bash/init.bash,              path: .profile                          }
        - { src: bash/init.bash,              path: .bash_profile                     }
        - { src: bash/init.bash,              path: .bashrc                           }
        - { src: gitconfig,                   path: .gitconfig                        }
        - { src: liquidprompt/liquid.theme,   path: .config/liquidprompt/liquid.theme }
        - { src: liquidprompt/liquidpromptrc, path: .config/liquidpromptrc            }
        - { src: ssh/config,                  path: .ssh/config                       }
        - { src: tmux.conf,                   path: .tmux.conf                        }
        - { src: ranger/rc.conf,              path: .config/ranger/rc.conf            }

    - name: Install required programs
      become: true
      apt:
        name: "{{ item }}"
      loop:
        - neovim
        - ranger
        - tmux
        - silversearcher-ag
        - htop
        - highlight

    - name: Clone vim configuration repository
      git:
        repo: https://github.com/binaryphile/dot_vim.git
        dest: "$HOME/.config/nvim"

    - name: Install vim-plug plugin manager
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "$HOME/.local/share/nvim/site/autoload/plug.vim"
        mode: '0644'

    - name: Check if Nix is already installed
      command: nix-env --version
      register: nix_installed
      ignore_errors: yes

    - name: Download and run Nix installation script if needed
      block:
        - get_url:
            url: https://install.lix.systems/lix
            dest: /tmp/lix-install.sh
            mode: '0755'

        - command: /tmp/lix-install.sh install --no-confirm

        - file:
            path: /tmp/lix-install.sh
            state: absent
      when: nix_installed.failed

    - name: Add home-manager channel
      command: >
        nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
      args:
        creates: "$HOME/.nix-channels"

    - name: Update Nix channels
      command: nix-channel --update
      args:
        creates: "$HOME/.nix-defexpr/channels/home-manager"

    - name: Install home-manager
      command: "nix-shell '<home-manager>' -A install"
      args:
        creates: "$HOME/.config/home-manager"

    - name: Create Nix configuration symlinks
      file:
        src: "$HOME/dotfiles/{{ item.src }}"
        path: "$HOME/{{ item.path }}"
        state: link
        force: yes
      loop:
        - { src: home.nix,   path: .config/home-manager/home.nix  }
        - { src: config.nix, path: .config/nixpkgs/config.nix     }

    - name: Apply home-manager configuration
      command: home-manager switch
      register: home_manager_result
      changed_when: "'Creating profile generation' in home_manager_result.stdout"
