- hosts: localhost
  tasks:
    - name: directories
      file:
        path:   $HOME/{{ item }}
        state:  directory
        mode:   '755'
      loop:
        - .config/liquidprompt
        - .config/ranger
        - tmp
      
    - name: ssh directory
      file:
        path:   $HOME/.ssh
        state:  directory
        mode:   '700'

    - name: clone dotfiles
      git:
        repo: https://github.com/binaryphile/dotfiles.git
        dest: $HOME/dotfiles
        
    - name: context link
      file:
        src:    contexts/work/crostini-bullseye
        path:   $HOME/dotfiles/context
        state:  link
        
    - name: dotfile links
      file:
        src:    $HOME/dotfiles/{{ item.src }}
        path:   $HOME/{{ item.path }}
        state:  link
        force:  yes
      loop:
        - { src: bash/init.bash,              path: .bash_profile                     }
        - { src: bash/init.bash,              path: .bashrc                           }
        - { src: gitconfig,                   path: .gitconfig                        }
        - { src: liquidprompt/liquid.theme,   path: .config/liquidprompt/liquid.theme }
        - { src: liquidprompt/liquidpromptrc, path: .config/liquidpromptrc            }
        - { src: ssh/config,                  path: .ssh/config                       }
        - { src: tmux.conf,                   path: .tmux.conf                        }
        - { src: ranger/rc.conf,              path: .config/ranger/rc.conf            }
  
    - name: install programs
      become: true
      apt: name={{ item }}
      loop:
        - neovim
        - ranger
        - tmux
        - silversearcher-ag
        - htop
    
