#!/usr/bin/env bash

Here=$(cd "$(dirname "$BASH_SOURCE")"; cd -P "$(dirname "$(readlink "$BASH_SOURCE" || echo .)")"; pwd)
source "$Here"/task.bash

task "set up ssh directory"
ok '[[ -e $HOME/.ssh ]]'
def mkdir -m 700 $HOME/.ssh

[[ ${1:=} == --trace ]] && { shift; set -x; }
summarize
