- hosts: localhost
  become: true
  tasks:
  - name: Install programs
    apt: name={{ item }}
    loop:
      - neovim
      - ranger
      - tmux
      - git
      - silversearcher-ag
  - import_role:
      name: user
