- hosts: localhost
  tasks:
  - name: Install programs
    become: true
    apt: name={{ item }}
    loop:
      - neovim
      - ranger
      - tmux
      - git
      - silversearcher-ag
      - htop
      - build-essential
      - gnupg2
  - import_role:
      name: user
