#!/usr/bin/env bash

Here=$(cd "$(dirname "$BASH_SOURCE")"; cd -P "$(dirname "$(readlink "$BASH_SOURCE" || echo .)")"; pwd)
source "$Here"/task.bash

main() {
  run mytask
}

task mytask echo 'hello world'

return 2>/dev/null
set -eu

main $*
summarize
