#!/usr/bin/env bash

Here=$(cd "$(dirname "$BASH_SOURCE")"; cd -P "$(dirname "$(readlink "$BASH_SOURCE" || echo .)")"; pwd)
source "$Here"/task.bash

main() {
  run mytask
  run taskgroup "
    mytask
  "
}

task mytask echo 'hello world'

group taskgroup; {
  task mytask echo 'hello taskgroup'
}

return 2>/dev/null
set -eu

main
summarize
