#!/usr/bin/env bash

Here=$(cd "$(dirname "$BASH_SOURCE")"; cd -P "$(dirname "$(readlink "$BASH_SOURCE" || echo .)")"; pwd)
source "$Here"/task.bash

main() {
  run mytask
  run taskgroup '
    othertask
  '
}

task mytask echo 'hello from mytask!'

group taskgroup
{
  task othertask echo 'hello from othertask!'
}

return 2>/dev/null
set -eu

main
summarize
