---

- name: directories
  file:
    path:   $HOME/{{ item }}
    state:  directory
    mode:   '755'
  loop:
    - .config/liquidprompt
    - tmp
    - scratch

- name: dotfile links
  file:
    src:    $HOME/dotfiles/{{ item.src }}
    path:   $HOME/{{ item.path }}
    state:  link
    force:  yes
  loop:
    - { src: bash/init.bash,              path: .bash_profile                     }
    - { src: bash/init.bash,              path: .bashrc                           }
    - { src: gitconfig,                   path: .gitconfig                        }
    - { src: liquidprompt/liquid.theme,   path: .config/liquidprompt/liquid.theme }
    - { src: liquidprompt/liquidpromptrc, path: .config/liquidpromptrc            }
    - { src: ssh/config,                  path: .ssh/config                       }
    - { src: tmux.conf,                   path: .tmux.conf                        }

- name: context link
  file:
    src:    contexts/office/macos
    path:   $HOME/dotfiles/context
    state:  link
