---

- name: directories
  file:
    path:   $HOME/{{ item }}
    state:  directory
    mode:   '755'
  loop:
    - .config/liquidprompt
    - tmp

- name: dotfile links
  file:
    src:    $HOME/dotfiles/{{ item.src }}
    path:   $HOME/{{ item.path }}
    state:  link
    force:  yes
  loop:
    - { src: bash/init.bash,              path: .bash_profile                     }
    - { src: bash/init.bash,              path: .bashrc                           }
    - { src: bash/init.bash,              path: .profile                          }
    - { src: bash/dir_colors,             path: .dir_colors                       }
    - { src: gitconfig,                   path: .gitconfig                        }
    - { src: liquidprompt/liquid.theme,   path: .config/liquidprompt/liquid.theme }
    - { src: liquidprompt/liquidpromptrc, path: .config/liquidpromptrc            }
    - { src: ssh/authorized_keys,         path: .ssh/authorized_keys              }
    - { src: ssh/config,                  path: .ssh/config                       }

- name: context link
  file:
    src:    contexts/home/original
    path:   $HOME/dotfiles/context
    state:  link
